/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f3f3f3',
        'secondary-container': '#e5e2e1',
        'surface-container': '#eeeeee',
        'on-tertiary-fixed': '#2f1500',
        'tertiary-container': '#e67e00',
        'surface-container-high': '#e8e8e8',
        'on-secondary-container': '#656464',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#00522a',
        'outline-variant': '#bccabc',
        secondary: '#5f5e5e',
        'on-surface-variant': '#3d4a3f',
        'surface-dim': '#dadada',
        'on-secondary-fixed': '#1c1b1b',
        'on-surface': '#1a1c1c',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#4e2700',
        'primary-fixed-dim': '#56df8a',
        'tertiary-fixed-dim': '#ffb77d',
        surface: '#f9f9f9',
        'inverse-surface': '#2f3131',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-background': '#1a1c1c',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#6e3900',
        'secondary-fixed-dim': '#c8c6c5',
        'on-primary-container': '#00391b',
        primary: '#006d39',
        'surface-tint': '#006d39',
        background: '#f9f9f9',
        outline: '#6d7b6e',
        error: '#ba1a1a',
        'inverse-primary': '#56df8a',
        'primary-container': '#0caf60',
        'on-primary-fixed': '#00210d',
        'tertiary-fixed': '#ffdcc3',
        'secondary-fixed': '#e5e2e1',
        'surface-bright': '#f9f9f9',
        'primary-fixed': '#75fca4',
        'surface-variant': '#e2e2e2',
        'surface-container-highest': '#e2e2e2',
        'inverse-on-surface': '#f1f1f1',
        tertiary: '#904d00',
        'on-secondary-fixed-variant': '#474646',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
